cmake_minimum_required(VERSION 4.2)
project(dsa_pratise)

set(CMAKE_CXX_STANDARD 20)

add_executable(dsa_pratise main.cpp
        Array-Hashing/TwoSum.cpp
        Array-Hashing/ShortestSubArray.cpp
        Array-Hashing/LongestSubstring.cpp
        stack/ValidParentheses.cpp
        stack/DailyTemperature.cpp
        tree/TreeTraversal.cpp
        tree/ValidBST.cpp
        Tree/LevelOrderTraversal.cpp
        Array-Hashing/ContainsDuplicate.cpp
        Array-Hashing/ValidAnagram.cpp
        Array-Hashing/GroupAnagram.cpp
        Array-Hashing/ProductExceptSelf.cpp
        Array-Hashing/LongestConsecutiveSequence.cpp
        binary-search/RotatedSortedArray.cpp
        binary-search/FindMinimum.cpp
        binary-search/KokoEatingBananas.cpp
        backtracking/Subset.cpp
        backtracking/Permutations.cpp
        raii/File.cpp
        raii/Buffer.cpp
        raii/DynamicArray.cpp
        Gameplay/WeaponSystem/Weapon.cpp
        Gameplay/WeaponSystem/Weapon.h
        Gameplay/WeaponSystem/Pistol.cpp
        Gameplay/WeaponSystem/Pistol.h
        Gameplay/WeaponSystem/Shotgun.cpp
        Gameplay/WeaponSystem/Shotgun.h
        Gameplay/WeaponSystem/RocketLauncher.cpp
        Gameplay/WeaponSystem/RocketLauncher.h
        Gameplay/WeaponSystem/WeaponFactory.cpp
        Gameplay/WeaponSystem/WeaponFactory.h
        Gameplay/WeaponSystem/Player.cpp
        Gameplay/WeaponSystem/Player.h
        Gameplay/Vector.cpp
        Gameplay/Vector.h
        Gameplay/AbilitySystem/Ability.cpp
        Gameplay/AbilitySystem/Ability.h
        Gameplay/TicTacToe/Cell.cpp
        Gameplay/TicTacToe/Cell.h
        Gameplay/TicTacToe/Board.cpp
        Gameplay/TicTacToe/Board.h
        Gameplay/TicTacToe/Player.cpp
        Gameplay/TicTacToe/Player.h
        Gameplay/TicTacToe/Game.cpp
        Gameplay/TicTacToe/Game.h
        Gameplay/TowerDefense/Enemy.cpp
        Gameplay/TowerDefense/Enemy.h
        Gameplay/TowerDefense/Path.cpp
        Gameplay/TowerDefense/Path.h
        Gameplay/TowerDefense/Projectile.cpp
        Gameplay/TowerDefense/Projectile.h
        Gameplay/TowerDefense/Tower.cpp
        Gameplay/TowerDefense/Tower.h
        Gameplay/TowerDefense/WaveManager.cpp
        Gameplay/TowerDefense/WaveManager.h
        Gameplay/TowerDefense/GameManager.cpp
        Gameplay/TowerDefense/GameManager.h
        binary-search/ShipWithinDays.cpp
        heap/KthLargest.cpp
        heap/TopKFrequentElements.cpp
        graph/NumberOfIslands.cpp
        linked-list/ReverseLinkedList.cpp
        linked-list/MergeTwoList.cpp
        tree/MaxDepthBinaryTree.cpp
        Gameplay/Snake/Position.cpp
        Gameplay/Snake/Position.h
        Gameplay/Snake/Direction.cpp
        Gameplay/Snake/Direction.h
        Gameplay/Snake/Board.cpp
        Gameplay/Snake/Board.h
        Gameplay/Snake/Snake.cpp
        Gameplay/Snake/Snake.h
        Gameplay/Snake/Food.cpp
        Gameplay/Snake/Food.h
        Gameplay/Snake/Game.cpp
        Gameplay/Snake/Game.h
        Array-Hashing/Intersection.cpp
        Array-Hashing/SubarraySum.cpp
        Two-Pointer/ValidPalindrome.cpp
        Tree/SameTree.cpp
        Tree/TreeNode.h
        Tree/SymmetricTree.cpp
        Tree/InvertBinaryTree.cpp
        Graph/FloodFill.cpp
        Stack/MinStack.cpp
        Stack/MinStack.h
        Math-Manipulation/Reverse.cpp
        Math-Manipulation/PalindromeNumber.cpp
        Math-Manipulation/PlusOne.cpp
        binary-search/Sqrt.cpp
        Two-Pointer/MergeSortedArray.cpp
        Two-Pointer/RemoveDuplicates.cpp
        Binary-Search/SearchInsertPosition.cpp
        Linked-List/ListNode.cpp
        Linked-List/ListNode.h
        RAII/ThreadSafeQueue.h
        Two-Pointer/ThreeSum.cpp
        Two-Pointer/ContainerWithMostWater.cpp
        Binary-Search/SearchMatrix.cpp
)
