cmake_minimum_required(VERSION 4.2)
project(dsa_pratise)

set(CMAKE_CXX_STANDARD 20)

add_executable(dsa_pratise main.cpp
        array/TwoSum.cpp
        array/ShortestSubArray.cpp
        string/LongestSubstring.cpp
        stack/ValidParentheses.cpp
        stack/DailyTemperature.cpp
        tree/TreeTraversal.cpp
        tree/ValidBST.cpp
        tree/BFS.cpp
        array/ContainsDuplicate.cpp
        string/ValidAnagram.cpp
        string/GroupAnagram.cpp
        array/ProductExceptSelf.cpp
        array/LongestConsecutiveSequence.cpp
        binary-search/RotatedSortedArray.cpp
        binary-search/FindMinimum.cpp
        binary-search/KokoEatingBananas.cpp
        backtracking/Subset.cpp
        backtracking/Permutations.cpp
        raii/File.cpp
        raii/Buffer.cpp
        fundamentals/DynamicArray.cpp
        weapon-system/Weapon.cpp
        weapon-system/Weapon.h
        weapon-system/Pistol.cpp
        weapon-system/Pistol.h
        weapon-system/Shotgun.cpp
        weapon-system/Shotgun.h
        weapon-system/RocketLauncher.cpp
        weapon-system/RocketLauncher.h
        weapon-system/WeaponFactory.cpp
        weapon-system/WeaponFactory.h
        weapon-system/Player.cpp
        weapon-system/Player.h
        move-a-to-b/Vector.cpp
        move-a-to-b/Vector.h
        ability-system/Ability.cpp
        ability-system/Ability.h
        tic-tac-toe/Cell.cpp
        tic-tac-toe/Cell.h
        tic-tac-toe/Board.cpp
        tic-tac-toe/Board.h
        tic-tac-toe/Player.cpp
        tic-tac-toe/Player.h
        tic-tac-toe/Game.cpp
        tic-tac-toe/Game.h
        tower-defense-game/Enemy.cpp
        tower-defense-game/Enemy.h
        tower-defense-game/Path.cpp
        tower-defense-game/Path.h
        tower-defense-game/Projectile.cpp
        tower-defense-game/Projectile.h
        tower-defense-game/Tower.cpp
        tower-defense-game/Tower.h
        tower-defense-game/WaveManager.cpp
        tower-defense-game/WaveManager.h
        tower-defense-game/GameManager.cpp
        tower-defense-game/GameManager.h
        binary-search/ShipWithinDays.cpp
        heap/KthLargest.cpp
        heap/TopKFrequentElements.cpp
        graph/NumberOfIslands.cpp
        linked-list/ReverseLinkedList.cpp
        linked-list/MergeTwoList.cpp
        tree/MaxDepthBinaryTree.cpp
)
